# This file is part of the Sylius package.
# (c) Paweł Jędrzejewski

imports:
    - { resource: '@OwlCoreBundle/Resources/config/app/fixtures/system_configuration.yaml' }

parameters:
    env(SYLIUS_FIXTURES_HOSTNAME): 'localhost'
    env(SYLIUS_FIXTURES_THEME_NAME): ~
