imports:
    - { resource: "@OwlCoreBundle/Resources/config/app/state_machine/owl_admin_user_registration.yml" }
    - { resource: "@OwlCoreBundle/Resources/config/app/state_machine/owl_equipment_event.yml" }
