owl_company:
    resources:
        company:
            classes:
                model: Owl\Component\Core\Model\Company
                controller: Owl\Bridge\SyliusResource\Controller\BaseController
