owl_company:
    resources:
        company:
            classes:
                model: Owl\Component\Core\Model\Company
                controller: Owl\Bridge\SyliusResourceBridge\Controller\BaseController
