# This file is part of the Sylius package.
# (c) Paweł Jędrzejewski

owl_user:
    resources:
        admin:
            user:
                classes:
                    model: Owl\Component\Core\Model\AdminUser
                    controller: Owl\Bundle\CoreBundle\Controller\UserController
                    interface: Owl\Component\Core\Model\AdminUserInterface
                    repository: Owl\Bundle\CoreBundle\Doctrine\ORM\AdminUserRepository
                    form: Owl\Bundle\CoreBundle\Form\Type\User\AdminUserType
        # oauth:
        #     user:
        #         hasher: false
        #         classes:
        #             model: Owl\Component\User\Model\UserOAuth
        #             interface: Owl\Component\User\Model\UserOAuthInterface
        #             controller: Sylius\Bundle\ResourceBundle\Controller\ResourceController
