owl_setting:
    resources:
        setting:
            classes:
                model: Owl\Component\Core\Model\Setting
                controller: Owl\Bridge\SyliusResourceBridge\Controller\BaseController
