owl_file:
    resources:
        suggestion:
            subject: "%owl.model.suggestion.class%"
            file:
                classes:
                    model: Owl\Component\Core\Model\SuggestionFile
                    form: Owl\Bundle\CoreBundle\Form\Type\Suggestion\SuggestionFileType
            uploader:
                classes:
                    model: "%owl.model.admin_user.class%"
        equipment:
            subject: "%owl.model.equipment.class%"
            file:
                classes:
                    model: Owl\Component\Core\Model\EquipmentFile
                    form: Owl\Bundle\CoreBundle\Form\Type\Equipment\EquipmentFileType
            uploader:
                classes:
                    model: "%owl.model.admin_user.class%"
        notification:
            subject: "%owl.model.notification.class%"
            file:
                classes:
                    model: Owl\Component\Core\Model\NotificationFile
                    form: Owl\Bundle\CoreBundle\Form\Type\Notification\NotificationFileType
            uploader:
                classes:
                    model: "%owl.model.admin_user.class%"
